---
title: "Vaccines"
author: "Hanna Rodrigues Ferreira"
date: "`r format(Sys.time(), '%d %B,%Y')`"
output:
  html_document:
    highlight: textmate
    includes: null
    theme: flatly
  pdf_document:
always_allow_html: true
---

```{r setup, message=FALSE,warning=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(ggplot2) 
library(dplyr) 
library(tidyr) 
library(stringr) 
library(maps)

```

```{r}

data <- read.csv('country_vaccinations.csv')

data2 <- read.csv('country_vaccinations_by_manufacturer.csv')

```

```{r}

head(data)

```

```{r}

head(data2)

```


```{r}

unique(data[c('country')])

```


```{r}

world <- map_data("world")

```



```{r}

library(ggplot2)
library(dplyr)
require(maps)
require(viridis)
theme_set(
  theme_void()
  )


world_map <- map_data("world")
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill="lightgray", colour = "white")


# Some EU Contries
some.eu.countries <- c(
  "Portugal", "Spain", "France", "Switzerland", "Germany",
  "Austria", "Belgium", "UK", "Netherlands",
  "Denmark", "Poland", "Italy", 
  "Croatia", "Slovenia", "Hungary", "Slovakia",
  "Czech republic"
)
# Retrievethe map data
some.eu.maps <- map_data("world", region = some.eu.countries)

# Compute the centroid as the mean longitude and lattitude
# Used as label coordinate for country's names
region.lab.data <- some.eu.maps %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))

region.lab.data

```



```{r}

ggplot(some.eu.maps, aes(x = long, y = lat)) +
  geom_polygon(aes( group = group, fill = region))+
  geom_text(aes(label = region), data = region.lab.data,  size = 3, hjust = 0.5)+
  scale_fill_viridis_d()+
  theme_void()+
  theme(legend.position = "none")

```



```{r}



```

```{r}



```

```{r}



```

```{r}



```

```{r}



```
