---
title: "Realizando análises bidimensionais - Exercício 4"
author: "Hanna Rodrigues Ferreira"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,message=FALSE}

library(dplyr)
library(ggplot2)

```


```{r}

tab <- as_tibble(read.csv("tabela2_1.csv", dec=",", sep=";",h=T))

glimpse(tab)

```

distribuição de freqüência conjunta para as variáveis grau de instrução e região de procedência

```{r}

freq1 <- addmargins(table(tab$grau_instrucao, tab$reg_procedencia))

freq1

```

distribuição de freqüência conjunta para as variáveis grau de instrução e região de procedência

```{r}

p_b <- freq1[2,4] / freq1[4,4]

p_b

```

Qual a porcentagem daqueles que têm o ensino médio e são do interior


```{r}

p_c <- freq1[2,2] / freq1[4,4]

p_c

```

Dentre os funcionários do interior, quantos por cento têm o ensino médio

```{r}

p_d <- freq1[2,2] / freq1[1,4]

p_d

```

```{r}

freq2 <- freq1

#freq2[1,:]/freq2[4,1]

```


