---
title: "Preços do Abacate"
author: "Hanna Rodrigues Ferreira"
date: "`r format(Sys.time(), '%d %B,%Y')`"
output:
  pdf_document:
  html_document:
    highlight: textmate
    includes: null
    theme: cosmo
always_allow_html: true
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

Dados do dataset [Avocado Prices](https://www.kaggle.com/neuromusic/avocado-prices), paleta de cor extraída de imagens de abacate :

```{r,warning=FALSE, message=FALSE}

library(gapminder)
library(tidyverse)
library(scales)

data <- read.csv('avocado.csv')

```

```{r,fig.height=3}

dark_green = "#384001"
green = "#B2BF4B"
brown = "#733410"
beige = "#F2E5A0"

show_col(c(dark_green, green,brown,beige))

```

```{r fig.align="center",fig.height=15}

data %>%
  ggplot(aes(x = AveragePrice,
             y = reorder(region, AveragePrice),
             color = type, fill = type)) +
  geom_boxplot() +
  scale_color_manual(values = c(brown,dark_green)) +
  scale_fill_manual(values = c(beige,green)) +
  theme_minimal() +
  guides(color = FALSE) +
  theme(legend.position = 'top') +
  labs(title = "Avocado's average price per region",y = NULL, x = "average price")

```