---
title: " Exercício 3"
author: "Hanna Rodrigues Ferreira"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,message=FALSE}

library(ggplot2)
library(ggExtra)
library(dplyr)
library(forcats)

```

Visualizações com base nos exemplos em : <https://livro.curso-r.com/8-1-o-pacote-ggplot2.html>

```{r}

imdb <- readr::read_rds("imdb.rds")

```

```{r}

imdb <- imdb %>% mutate( lucro = receita - orcamento )

glimpse(imdb)

```



```{r}

graf <- imdb %>%
  filter(!is.na(nota_imdb)) %>% 
  ggplot() + 
  geom_point(mapping = aes(x = lucro, y = nota_imdb , color = nota_imdb)) +
  scale_color_gradient(low = "red", high = "green") +
  geom_vline(xintercept = 0)

graf <- ggMarginal(graf, type="histogram",fill = "darkblue")

show(graf)

```

```{r}

#imdb %>% select(diretor) %>% arrange(desc())

```


```{r}

imdb %>% 
  filter(diretor == "Steven Spielberg") %>% 
  group_by(ano) %>% 
  summarise(nota_media = mean(nota_imdb, na.rm = TRUE)) %>% 
  mutate(nota_media = round(nota_media, 1)) %>% 
  ggplot(aes(x = ano, y = nota_media)) +
  geom_smooth(se = FALSE, method = "lm", color = "red") +
  geom_line() +
  geom_label(aes(label = nota_media)) +
  coord_cartesian(ylim = c(5.5, 9))


```


```{r}

imdb %>%
  mutate(nota_imdb = floor(nota_imdb)) %>% 
  count(nota_imdb) %>%
  filter(!is.na(nota_imdb)) %>% 
  top_n(10, n) %>%
  ggplot() +
  geom_col(aes(x = nota_imdb, y = n, fill = nota_imdb), show.legend = FALSE) +
  geom_label(aes(x = nota_imdb, y = n/2, label = n)) +
  coord_flip()

```

```{r}

imdb %>% 
  filter(!is.na(cor)) %>%
  group_by(cor) %>% 
  ggplot() +
  geom_boxplot(aes(x = cor, y = nota_imdb)) +
  labs(
    x = "Cor",
    y = "Nota imdb",
    color = "blue",
    title = "Boxplot das notas pela cor do filme"
    )

```