---
title: "Analisando e explorando a base CD-Brasil"
author: "Hanna Rodrigues Ferreira"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r,message=FALSE}

library(dplyr)
library(ggplot2)

```


```{r}

tab <- read.csv("brasilcd.csv", dec=",", sep=";",h=T)

glimpse(tab)

```

distribuição de frequencia das variáveis população e densidade populacional

```{r}

tab2 = tab

tab2$População <- cut(tab2$População, 
    breaks=c(0, 1000000, 5000000, 10000000, 40000000), 
    labels=c("0 -> 1M","1M -> 5M","5M -> 10M","10M -> 40M"))

tab2$Densidade <- as.numeric(tab2$Densidade)

tab2$Densidade <- cut(tab2$Densidade, 
    breaks=c(-Inf, 5, 25, 50, 75,100,500), 
    labels=c("0:5","5:25","25:50", "50:75","75:100","100:500"))

addmargins(table(tab2$População, tab2$Densidade))

```

quantis da variável população

```{r}

quantile(tab$População, na.rm = T)

```

desenhe o bosxplot e faça comentários

```{r}

tab %>% 
  ggplot() +
  geom_boxplot(aes(y = População)) +
  labs(
    y = "População",
    color = "blue"
    )

```

represente graficamente a população por regiões geográficas

```{r}




```


